const database = [
  {
    id: '1',
    name: 'Services',
    icon: 'user',
    route: '/services',
  },
  {
    id: '11',
    name: 'Create Services',
    menuParentId: '-1',
    breadcrumbParentId: '1',
    icon: 'user',
    route: '/services/create',
  },
  {
    id: '12',
    name: 'Update Service',
    menuParentId: '-1',
    breadcrumbParentId: '1',
    icon: 'user',
    route: '/services/update/:id',
  },
  {
    id: '2',
    name: 'Departments',
    icon: 'user',
    route: '/departments',
  },
  {
    id: '21',
    name: 'Create Department',
    menuParentId: '-1',
    breadcrumbParentId: '2',
    icon: 'user',
    route: '/departments/create',
  },
  {
    id: '22',
    name: 'Update Department',
    menuParentId: '-1',
    breadcrumbParentId: '2',
    icon: 'user',
    route: '/departments/update',
  },
  {
    id: '3',
    name: 'Categories',
    icon: 'user',
    route: '/categories',
  },
  {
    id: '31',
    name: 'Create Category',
    menuParentId: '-1',
    breadcrumbParentId: '3',
    icon: 'user',
    route: '/categories/create',
  },
  {
    id: '4',
    name: 'Sub Categories',
    icon: 'user',
    route: '/sub_categories',
  },
  {
    id: '41',
    name: 'Create Sub Category',
    menuParentId: '-1',
    breadcrumbParentId: '4',
    icon: 'user',
    route: '/sub_categories/create',
  },
  {
    id: '5',
    name: 'Parts',
    icon: 'user',
    route: '/parts',
  },
  {
    id: '51',
    name: 'Create Part',
    menuParentId: '-1',
    breadcrumbParentId: '5',
    icon: 'user',
    route: '/parts/create',
  },
  {
    id: '6',
    name: 'Offers',
    icon: 'user',
    route: '/offers',
  },
  {
    id: '61',
    name: 'Create Offer',
    menuParentId: '-1',
    breadcrumbParentId: '6',
    icon: 'user',
    route: '/offers/create',
  },
  {
    id: '7',
    name: 'Packages',
    icon: 'user',
    route: '/packages',
  },
  {
    id: '71',
    name: 'Create Package',
    menuParentId: '-1',
    breadcrumbParentId: '7',
    icon: 'user',
    route: '/packages/create',
  },
  {
    id: '8',
    name: 'Admin Orders',
    icon: 'user',
    route: '/admin_orders',
  },
  {
    id: '10',
    name: 'Pending Orders',
    icon: 'user',
    route: '/pending_orders',
  },
  {
    id: '9',
    name: 'Service Provider',
    icon: 'user',
    route: '/service_providers',
  },
  {
    id: '91',
    name: 'Create Provider',
    menuParentId: '-1',
    breadcrumbParentId: '9',
    icon: 'user',
    route: '/service_providers/create/:id',
  },
  // {
  //   id: '91',
  //   name: 'Internal Service Providers',
  //   menuParentId: '9',
  //   breadcrumbParentId: '1',
  //   icon: 'user',
  //   route: '/reports/service_providers',
  // },
  // {
  //   id: '92',
  //   name: 'External Service Providers',
  //   menuParentId: '9',
  //   breadcrumbParentId: '2',
  //   icon: 'user',
  //   route: '/reports/external_services',
  // },
  {
    id: '11',
    name: 'Promo Code',
    icon: 'user',
    route: '/promo_code',
  },
  {
    id: '111',
    name: 'Create Promo Code',
    menuParentId: '-1',
    breadcrumbParentId: '11',
    icon: 'user',
    route: '/promo_code/create',
  },
  {
    id: '12',
    name: 'Invoices',
    icon: 'user',
    route: '/invoices',
  },
  {
    id: '13',
    name: 'Zone',
    icon: 'user',
    route: '/zone',
  },
  {
    id: '131',
    name: 'Create Zone',
    menuParentId: '-1',
    breadcrumbParentId: '13',
    icon: 'user',
    route: '/zone/create',
  },
]

export default database
